apiVersion:: v1 
kind: Pod
metadata:
  name: annotations
  namespace: roboshop
  labels:
   project: roboshop
   command: frontend
   environment: dev
  annotations:
    imageregistry: "https://hub.docker.com/" 
  spec:
   containers:
   - name: nginx
     image: nginx 