apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests: #soft limit (start)
        memory: "64Mi" #ram
        cpu: "100m"  #disk --cpu
      limits: #hard limit (max) beyond this limit resource will not move
        memory: "128Mi"
        cpu: "500m"
