apiVersion: v1
kind: Service
metadata:
  name: nginx-service           # Name of the Service  
spec:
  selector:  #labels are used as selectors
    project: roboshop
    component: frontend
    environment: dev                  # Matches Pods with these labels
    
  ports:
    - name: http
      protocol: TCP           # Protocol (TCP/UDP/SCTP)
      port: 80                # Port exposed by the Service
      targetPort: 80       # Port on the Pod container
 # type: ClusterIP             # Default type (internal access only)
