apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx   # Container image (with version tag)
      ports:
        - containerPort: 80 # Port exposed by the container
     


